application: firiplanning
version: production
runtime: python27
api_version: 1
threadsafe: yes


libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
- url: /workers/.*
  script: workers.application
  login: admin
- url: /.*
  login: required
  secure: always
  script: main.application
